# Builds site/catalog/clips.js from site/catalog/clips-meta.json.
# Fails if a video file exists without a metadata entry, or an entry points at a missing file,
# so every rendered clip is guaranteed to appear on the site.
# Usage: python scripts/build_catalog.py [--allow-missing]   (run from the repository root)
# --allow-missing writes the catalog anyway (development only); the final build must pass without it.
import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
# Clip files live under media/; their "file" fields are relative to it.
ASSETS = ROOT / "media"
META = ROOT / "site" / "catalog" / "clips-meta.json"
OUT = ROOT / "site" / "catalog" / "clips.js"
CLIP_DIRS = ["clips", "engine", "tools", "edit"]
REQUIRED = ["id", "cat", "file", "title", "aka", "tool", "runs", "notice", "use", "prompt"]


def main() -> int:
    meta = json.loads(META.read_text(encoding="utf-8"))
    problems = []
    seen = set()
    for m in meta:
        missing = [k for k in REQUIRED if not m.get(k)]
        if missing:
            problems.append(f"{m.get('id', '?')}: missing fields {missing}")
        if m["id"] in seen:
            problems.append(f"duplicate id {m['id']}")
        seen.add(m["id"])
        if not (ASSETS / m["file"]).is_file():
            problems.append(f"{m['id']}: file not found {m['file']}")
    described = {m["file"] for m in meta}
    for d in CLIP_DIRS:
        for f in sorted((ASSETS / d).glob("*.mp4")):
            rel = f.relative_to(ASSETS).as_posix()
            if rel not in described:
                problems.append(f"no metadata for {rel}")
    if problems:
        print("CATALOG PROBLEMS:\n  " + "\n  ".join(problems))
        if "--allow-missing" not in sys.argv:
            return 1
        meta = [m for m in meta if (ASSETS / m["file"]).is_file()]
    OUT.write_text(
        "// Generated by scripts/build_catalog.py from clips-meta.json. Do not edit by hand.\n"
        "window.CLIPS = " + json.dumps(meta, indent=1, ensure_ascii=False) + ";\n",
        encoding="utf-8",
    )
    print(f"wrote {OUT.relative_to(ROOT)} with {len(meta)} clips")
    return 0


if __name__ == "__main__":
    sys.exit(main())
